<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WolfGymLauncher</AssemblyName>
    <RootNamespace>WolfGymLauncher</RootNamespace>
    <AssemblyTitle>Wolf Gym</AssemblyTitle>
    <Product>Wolf Gym</Product>
    <Description>Gestion de gimnasio y control biometrico</Description>
    <Company>Wolf Gym</Company>
    <Authors>Wolf Gym</Authors>
    <Copyright>Copyright Wolf Gym</Copyright>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ApplicationIcon>Assets\WolfGymLauncher.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\WolfGymLauncher.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
