<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.20" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Excluir demos de la compilación -->
    <Compile Remove="C#\**" />
    <Compile Remove="c\**" />
    <EmbeddedResource Remove="C#\**" />
    <EmbeddedResource Remove="c\**" />
    <None Remove="C#\**" />
    <None Remove="c\**" />
  </ItemGroup>

</Project>
