<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <Compile Include="../../biometric-service/Data/LocalDatabaseConfiguration.cs" Link="LocalDatabaseConfiguration.cs" />
  </ItemGroup>
</Project>
